### ISSUE TITLE
Requiring the module causes a syntax error on node 0.12.7. 

### ISSUE THREAD

**Issue by baetheus** [shoutpoint-inc/api-js-sdk#5]
When attempting to use the api module in a node 0.12.7 repl, exports throws a syntax error.

To reproduce:

    brandon@tesla ~/Code/test ❯ node -v
    v0.12.7
    brandon@tesla ~/Code/test ❯ npm install shoutpoint-api-sdk
    shoutpoint-api-sdk@0.4.4 node_modules/shoutpoint-api-sdk
    └── q@1.4.1
    brandon@tesla ~/Code/test ❯ node
    > var shoutpoint = require('shoutpoint-api-sdk');
    /Users/brandon/Code/test/node_modules/shoutpoint-api-sdk/modules/phoneNumbers/phonenumbers.js:30
            var query = querystring.stringify({search_by, search_on});
                                                        ^
    SyntaxError: Unexpected token ,
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/Users/brandon/Code/test/node_modules/shoutpoint-api-sdk/index.js:5:20)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)

However, it seems to work fine with node 5.3.0:

    brandon@tesla ~/Code/test ❯ node -v
    v5.3.0
    brandon@tesla ~/Code/test ❯ npm install shoutpoint-api-sdk
    /Users/brandon/Code/test
    └─┬ shoutpoint-api-sdk@0.4.4 
      └── q@1.4.1 

    npm WARN ENOENT ENOENT: no such file or directory, open '/Users/brandon/Code/test/package.json'
    npm WARN EPACKAGEJSON test No description
    npm WARN EPACKAGEJSON test No repository field.
    npm WARN EPACKAGEJSON test No README data
    npm WARN EPACKAGEJSON test No license field.
    brandon@tesla ~/Code/test ❯ node
    > var shoutpoint = require('shoutpoint-api-sdk');
    undefined

To fix:

Either specify node versions that the module works for or fix the syntax error.

Thanks!

**Comment by patrick-martin-shoutpoint** [comment]
@asontha Let's make sure this library targets ES5. The syntax error is an ES6 feature: object literal property shorthand. First step, change the phonenumbers.js:30 line to `var query = querystring.stringify({search_by:seatch_by, search_on:search_on});`

**Comment by asontha** [comment]
This should be fixed and compatibility with ES5 and Node 4 should be working.
